spring:
  application:
    name: demo-jwt
  config:
    import:
      - classpath:/conf/application-local-h2.yml
      - classpath:/conf/application-local-log.yml
  profiles:
    active: local
    default: local
  mvc:
    throw-exception-if-no-handler-found: true
management:
  endpoints:
    web:
      exposure:
        include: mappings,health,info,metrics
  endpoint:
    health:
      show-details: always
server:
  error:
    whitelabel:
      enabled: false
